version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    networks:
      - proxy
    environment:
      APP_ENV: local
      APP_DEBUG: "false"
      SITE_OWNER: mail@example.com
      APP_KEY: SomeRandomStringOf32CharsExactly
      DEFAULT_LANGUAGE: es_ES
      DEFAULT_LOCALE: equal
      TZ: Europe/Madrid
      TRUSTED_PROXIES: ""
      LOG_CHANNEL: stack
      PAPERTRAIL_HOST: ""
      PAPERTRAIL_PORT: ""
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: info
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: secret_firefly_password
      DB_SOCKET: ""
      MYSQL_USE_SSL: "false"
      MYSQL_SSL_VERIFY_SERVER_CERT: "true"
      MYSQL_SSL_CAPATH: /etc/ssl/certs/
      MYSQL_SSL_CA: ""
      MYSQL_SSL_CERT: ""
      MYSQL_SSL_KEY: ""
      MYSQL_SSL_CIPHER: ""
      PGSQL_SSL_MODE: prefer
      PGSQL_SSL_ROOT_CERT: "null"
      PGSQL_SSL_CERT: "null"
      PGSQL_SSL_KEY: "null"
      PGSQL_SSL_CRL_FILE: "null"
      PGSQL_SCHEMA: public
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      REDIS_SCHEME: tcp
      REDIS_PATH: ""
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: "6379"
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_DB: '"0"'
      REDIS_CACHE_DB: '"1"'
      COOKIE_PATH: '"/"'
      COOKIE_DOMAIN: ""
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      MAIL_MAILER: log
      MAIL_HOST: "null"
      MAIL_PORT: "2525"
      MAIL_FROM: changeme@example.com
      MAIL_USERNAME: "null"
      MAIL_PASSWORD: "null"
      MAIL_ENCRYPTION: "null"
      MAILGUN_DOMAIN: ""
      MAILGUN_SECRET: ""
      MAILGUN_ENDPOINT: api.mailgun.net
      MANDRILL_SECRET: ""
      SPARKPOST_SECRET: ""
      SEND_REGISTRATION_MAIL: "true"
      SEND_ERROR_MESSAGE: "true"
      SEND_LOGIN_NEW_IP_WARNING: "true"
      SEND_REPORT_JOURNALS: "true"
      ENABLE_EXTERNAL_MAP: "false"
      MAP_DEFAULT_LAT: "51.983333"
      MAP_DEFAULT_LONG: "5.916667"
      MAP_DEFAULT_ZOOM: "6"
      AUTHENTICATION_GUARD: web
      AUTHENTICATION_GUARD_HEADER: REMOTE_USER
      AUTHENTICATION_GUARD_EMAIL: ""
      CUSTOM_LOGOUT_URL: ""
      DISABLE_FRAME_HEADER: "false"
      DISABLE_CSP_HEADER: "false"
      TRACKER_SITE_ID: ""
      TRACKER_URL: ""
      ALLOW_WEBHOOKS: "false"
      STATIC_CRON_TOKEN: ""
      DKR_BUILD_LOCALE: "false"
      DKR_CHECK_SQLITE: "true"
      DKR_RUN_MIGRATION: "true"
      DKR_RUN_UPGRADE: "true"
      DKR_RUN_VERIFY: "true"
      DKR_RUN_REPORT: "true"
      DKR_RUN_PASSPORT_INSTALL: "true"
      APP_NAME: FireflyIII
      BROADCAST_DRIVER: log
      QUEUE_DRIVER: sync
      CACHE_PREFIX: firefly
      PUSHER_KEY: ""
      IPINFO_TOKEN: ""
      PUSHER_SECRET: ""
      PUSHER_ID: ""
      DEMO_USERNAME: ""
      DEMO_PASSWORD: ""
      IS_HEROKU: "false"
      FIREFLY_III_LAYOUT: v1
      APP_URL: https://finances.home
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.finances.rule=Host(`finances.home`)"
      - "traefik.http.routers.finances.entrypoints=websecure"
      - "traefik.http.services.finances.loadbalancer.server.port=8080"
      - "traefik.http.routers.finances.service=finances"
      - "traefik.http.routers.finances.tls=true"
#    ports:
#      - 8080
    depends_on:
      - db
  db:
    image: mariadb    
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: secret_firefly_password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: firefly
      MYSQL_PORT: "3306"
      MYSQL_PASSWORD: secret_firefly_password
      MYSQL_DATABASE: firefly
      DB_SOCKET: ""
      MYSQL_USE_SSL: "false"
      MYSQL_SSL_VERIFY_SERVER_CERT: "true"
      MYSQL_SSL_CAPATH: /etc/ssl/certs/
      MYSQL_SSL_CA: ""
      MYSQL_SSL_CERT: ""
      MYSQL_SSL_KEY: ""
      MYSQL_SSL_CIPHER: ""
      PGSQL_SSL_MODE: prefer
      PGSQL_SSL_ROOT_CERT: "null"
      PGSQL_SSL_CERT: "null"
      PGSQL_SSL_KEY: "null"
      PGSQL_SSL_CRL_FILE: "null"
      PGSQL_SCHEMA: public
    labels:
      - "traefik.enable=false"
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    environment:
      FIREFLY_III_URL: https://finances.home
      VANITY_URL: ""
      FIREFLY_III_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMGQ4NzY5MjgxZmZjYzFkZDhmYWViZGViYzExNjg4MzM3YzNjMzM4YmJmNjJmMDMzZWM5YTBjNGQxZDEyYWU2NWY1YTRmYjc5MjQwM2RhNjQiLCJpYXQiOjE2NzE3OTI1MDIuMDc2MjU2LCJuYmYiOjE2NzE3OTI1MDIuMDc2MjU4LCJleHAiOjE3MDMzMjg1MDIuMDYzOTczLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.mLSk5cSBUoQ_CVILVSKEZa-SBAjIVaxhbyZDiPL5k63i5IfZ910i5wgYBPze5SQgnnurX9N49S7uIdMyJLvA6bIuEqVpYT8MnGNOZWrpZ3clDzqB1rNf71RoafP1U5MOlnlGNKrCSUgdHueiH9X4B-tUgY0lqnZAvtIZeB_vd5uquWTU9B1g2JnAu3EakLRTCKd73Cs02CbMPBfmfl3-Wp13fDi8sUkf0OABtSczEMd6oJvJMXPFC4iWb8W3Tx84DeUT_S9Ol3UbIOYKeXuZFNO4bOz-2a972DBzup9lvvASyYXDkxyCCSPWCdhWFVw3B098-Z3G-z31Bxk6EfSMjaJ-lT1c0_y3HILEL4mXTUKeJ6rB1e8QSzGi91VEyzwtJtSI4W3VkJCs3kUEkbLsrDnmJCZDFzZYoDEjRNeCaHU7ZD-9eZcbsAo6bZpqhCzBh5C8p7pr1irg98CHFzbEk6YR_wQgg3cPMdTjoKIP8Oz8Kh-QsuuQ0EwJebsINkN4AOmu_EWsp2UCX2keMH8LsqmLScGu0OXFlXUce1vYpLEsecJnrYKWb4u2HiG_NBKiiQqZHh3fWXI2yqLw9an1hVCha4oq_kvHrntU3Q4HB5BFdgrG2k1CqYphfDPcFmw5br6cbj5W6tZo6Ifkgxo2jDnAx-8lBXrpeDDof0MHYZQ
      FIREFLY_III_CLIENT_ID: ""
      NORDIGEN_ID: ""
      NORDIGEN_KEY: ""
      NORDIGEN_SANDBOX: "false"
      SPECTRE_APP_ID: ""
      SPECTRE_SECRET: ""
      USE_CACHE: "false"
      IGNORE_DUPLICATE_ERRORS: "false"
      AUTO_IMPORT_SECRET: ""
      CAN_POST_AUTOIMPORT: "false"
      CAN_POST_FILES: "false"
      IMPORT_DIR_WHITELIST: ""
      VERIFY_TLS_SECURITY: "true"
      JSON_CONFIGURATION_DIR: ""
      CONNECTION_TIMEOUT: "31.41"
      APP_ENV: local
      APP_DEBUG: "false"
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      TRUSTED_PROXIES: ""
      TZ: Europe/Amsterdam
      ASSET_URL: ""
      ENABLE_MAIL_REPORT: "false"
      EXPECT_SECURE_URL: "false"
      MAIL_MAILER: ""
      MAIL_DESTINATION: noreply@example.com
      MAIL_FROM_ADDRESS: noreply@example.com
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: "2525"
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: "null"
      MAILGUN_DOMAIN: ""
      MAILGUN_SECRET: ""
      MAILGUN_ENDPOINT: ""
      POSTMARK_TOKEN: ""
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: "120"
      IS_EXTERNAL: "false"
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: "null"
      REDIS_PORT: "6379"
      REDIS_DB: '"0"'
      REDIS_CACHE_DB: '"1"'
      TRACKER_SITE_ID: ""
      TRACKER_URL: ""
      APP_NAME: DataImporter
      APP_URL: https://import.finances.home
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.moneyimporter.rule=Host(`import.finances.home`)"
      - "traefik.http.routers.moneyimporter.entrypoints=websecure"
      - "traefik.http.services.moneyimporter.loadbalancer.server.port=8080"
      - "traefik.http.routers.moneyimporter.service=moneyimporter"
      - "traefik.http.routers.moneyimporter.tls=true"
    depends_on:
      - app
    networks:
      - proxy

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  proxy:
    external: true

