version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      - traefik.http.routers.app-secure.entrypoints:websecure
      - traefik.docker.network:portainer_default
      - traefik.enable:true
      - traefik.http.routers.app-secure.rule	Host(`money.warehouse.lan`)
    ports:
      - 8080
    depends_on:
      - db
  db:
    image: mariadb    
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    env_file: .fidi.env
    labels:
      - traefik.http.routers.app-secure.entrypoints:websecure
      - traefik.docker.network:portainer_default
      - traefik.enable:true
      - traefik.http.routers.app-secure.rule	Host(`moneyimporter.warehouse.lan`)
    ports:
      - 8081:8080
    depends_on:
      - app
volumes:
  firefly_iii_upload:
  firefly_iii_db:

